from django.urls import path
from . import views

# Paths are relative to /api/ (mounted in epharma_site/urls.py).
urlpatterns = [
    path("config", views.config),
    path("health", views.health),
    path("taxonomy", views.taxonomy),
    path("cms", views.cms_list),
    path("cms/<str:slug>", views.cms_page),
    path("register/send-otp", views.send_otp),
    path("register", views.register),
    path("me/documents", views.me_documents),
    path("me", views.me),
    path("login", views.login),
    path("logout", views.logout),
    path("medicines", views.medicines),
    path("medicines/<int:id>", views.medicine_detail),
    path("my-medicines", views.my_medicines),
    path("doctors", views.doctors),
    path("payments/create", views.payments_create),
    path("orders", views.orders),
    path("orders/<int:id>", views.order_detail),
    path("appointments", views.appointments),
    path("appointments/<int:id>", views.appointment_detail),
    path("appointments/<int:id>/messages", views.appointment_messages),
    path("appointments/<int:id>/room", views.appointment_room),
    path("refills", views.refills),
    path("prescriptions", views.prescriptions),
    path("prescriptions/upload", views.prescriptions_upload),
    path("notifications", views.notifications),
    path("notifications/read", views.notifications_read),
    path("earnings", views.earnings),
    path("admin/users", views.admin_users),
    path("admin/users/<int:id>", views.admin_user_detail),
    path("admin/stats", views.admin_stats),
    path("admin/reports", views.admin_reports),
    path("admin/audit", views.admin_audit),
    path("admin/taxonomy", views.admin_taxonomy),
    path("admin/taxonomy/<int:id>", views.admin_taxonomy_detail),
    path("admin/cms/<str:slug>", views.admin_cms),
]
